### ISSUE TITLE
SerialPortDevice missing

### ISSUE THREAD

**Issue by ondrasvoboda** [dotMorten/NmeaParser#101]
Hi,
I've noticed that in version 2.2.1 the class SerialPortDevice is missing in .NET Framework build. I think it's because of the bug in constant definition:
```
<PropertyGroup Condition="'$(TargetFramework)' == 'net451'">
    <DefineConstants>$(DefineConstants);NETFX</DefineConstants>
</PropertyGroup>
```
net451 should be net452

Could you please check?

**Comment by dotMorten** [comment]
@ondrasvoboda Oops! Thank you. Fix incoming...

**Comment by dotMorten** [comment]
v2.2.2 published

**Comment by ondrasvoboda** [comment]
Thanks!

**Comment by SonicScholar** [comment]
> v2.2.2 published

@dotMorten Could you create quickly tag 2.2.2 here?
I spent a little bit of time trying to reconcile the 2.2.2 latest version on NuGet and the release here on your GitHub. Thanks!

**Comment by dotMorten** [comment]
@SonicScholar Thanks for the reminder. Looks like I forgot to tag that release. Done!
