### ISSUE TITLE
Add net462 or net472 as target framework for nuget package

### ISSUE THREAD

**Issue by glopesdev** [dotMorten/NmeaParser#106]
The current NuGet package targets both netstandard2.0 and net45.

.NET 4.5 seems to require additional dependencies ([Microsoft.NETFramework.ReferenceAssemblies](https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/)) which are not required by netstandard2.0.

Unfortunately, when creating a C# project targeting net462 or net472 (both of which implement netstandard2.0), the NuGet client prefers the .NET 4.5 target instead of netstandard2.0 and the redundant extra dependencies are imported into the project.

Would it be possible to add a net462 or net472 target to the package to avoid pulling these extra dependencies?

**Comment by dotMorten** [comment]
There shouldn’t be any extra dependencies pulled in. Everything 45 has, is supported by 462. Could you talk a little bit more about what issue you are actually hitting?

> when creating a C# project targeting net462 or net472 (both of which implement netstandard2.0), the NuGet client prefers the .NET 4.5 target instead of netstandard2.0

that is the correct TFM fallback.
