### ISSUE TITLE
Almost works with Maui, missing three classes.

### ISSUE THREAD

**Issue by gmarbury** [dotMorten/NmeaParser#115]
When referenced from Maui it links but the platform-specific files listed below are not available. In addition, the BluetoothDevice.UWP.cs file needs to check for #if NETFX_CORE || WINDOWS

**Files**
EAAccessoryDevice.iOS.cs
BluetoothDevice.Android.cs
BluetoothDevice.UWP.cs  

https://www.nuget.org/packages/SharpGIS.NmeaParser/2.2.2

**Comment by dotMorten** [comment]
Maui isn’t supported. See .net6 branch: 
https://github.com/dotMorten/NmeaParser/tree/net6
