### ISSUE TITLE
UWP Serial Communication NmeaParser 

### ISSUE THREAD

**Issue by lzel** [dotMorten/NmeaParser#25]
Hello,
I am building Windows Universal Application with USB serial communication. For this reason I am trying to use NMEA Parser, which I installed by Nuget Manager from SharpGIS.NMEAParser.
Here is my code:

`private async System.Threading.Tasks.Task PortSetup(string portName)
{
    var selector = SerialDevice.GetDeviceSelector(portName);
    var devices = await DeviceInformation.FindAllAsync(selector);
    if (devices.Any())
    {
        var deviceInfo = devices.First();
        SerialDevice serialPort = await SerialDevice.FromIdAsync(deviceInfo.Id);
        serialPort.BaudRate = 9600;
        serialPort.DataBits = 8;
        serialPort.Parity = SerialParity.None;
        serialPort.StopBits = SerialStopBitCount.One;

        var device = new NmeaParser.SerialPortDevice(serialPort)
        device.MessageReceived += Device_MessageReceived;
        await device.OpenAsync();
    }
}
 private void Device_MessageReceived(object sender, NmeaParser.NmeaMessageReceivedEventArgs e)
 {
      string message = e.Message.ToString();
 }`

And in Package.appxmanifest:

`<DeviceCapability Name="serialcommunication" > 
    <Device Id="any"> 
      <Function Type="name:serialPort"/> 
    </Device> 
</DeviceCapability> `

Everything as in "https://github.com/dotMorten/NmeaParser/wiki/Using-in-a-Windows-Universal-App-(SerialPort)", just I added "await device.CloseAsync();" and await "device.OpenAsync();".
The program is working good up to creating an event: "device.MessageReceived += Device_MessageReceived;" A problem is that the event never works. It does not get messages from serial port.
Does anybody have any idea?

**Comment by dotMorten** [comment]
Are you sure those parameters are correct? Is you device running at 9600 (check the device specifications)? Is yoru device using NMEA or configured to use NMEA? Are any other NMEA client applications able to connect to it and use it?
