### ISSUE TITLE
SerialDevice.FromIdAsync trtun NULL

### ISSUE THREAD

**Issue by Eg-Virus** [dotMorten/NmeaParser#26]
Hi,
i'm using your demo to check the Serial/Bluetooth connectivity but i get error because i can't get the device from SerialDevice.FromIdAsync , even the selector is not null.

Thank you

**Comment by dotMorten** [comment]
@Eg-Virus Do you know for sure your device is paired and listed as a serial device? Did you modify your app manifest to allow connecting to serial devices?
I'd recommend asking the Microsoft MSDN forums, since getting the serial device is a Windows API thing, and not related to this project.

**Comment by Eg-Virus** [comment]
Yes,
and Yes i added the manifest block to allow the serial port.

Thank you anyway.
