### ISSUE TITLE
NMEA GGA FixTime and TimeSinceLastDgpsUpdate

### ISSUE THREAD

**Issue by terribletim** [dotMorten/NmeaParser#27]
Project: **NmeaParser.Shared**
Namesapce:  **NmeaParser.Nmea.Gps**
Class: **GPGGA**
in  **OnLoadMessage**
`TimeSinceLastDgpsUpdate = StringToTimeSpan(message[0]);`
should be `TimeSinceLastDgpsUpdate = StringToTimeSpan(message[12]);` 

Also, decoding FixTime would be helpful as per GPGLL:
`FixTime = StringToTimeSpan(message[0]);`

Thanks very much for sharing project.

**Comment by dotMorten** [comment]
Thanks!
