### ISSUE TITLE
UWP SerialDevice buffering

### ISSUE THREAD

**Issue by polygreg** [dotMorten/NmeaParser#28]
Hiya,
First of all - great library, I love it!
I had a small issue (and quick fix) using this library with a SerialDevice on Windows 10 IoT (15043) on a Raspberry Pi 3. 
Effectively, it took an incredibly long time to start receiving events (several mins) - it turns out that converting the input stream from the serial device with "AsStreamForRead" was buffering a huge amount before returning any data.

I simply amended the following in your SerialPortDevice:

protected override Task<System.IO.Stream> OpenStreamAsync()
		{
			return Task.FromResult<System.IO.Stream>(m_port.InputStream.AsStreamForRead());
		}

to

protected override Task<System.IO.Stream> OpenStreamAsync()
		{
			return Task.FromResult<System.IO.Stream>(m_port.InputStream.AsStreamForRead(0));
		}

The overloaded version disables any additional stream buffering, I got instant triggering of message events following that.

I don't know if it's because the Pi3 has a different UART or it was some other reason, either way just logging it here in case it crops up for anyone else :)

Cheers

**Comment by dotMorten** [comment]
Great find! I've checked in the fix.
