### ISSUE TITLE
Not all Satellites are being parsed in GPGSV

### ISSUE THREAD

**Issue by gordonpagan** [dotMorten/NmeaParser#29]
On the sample data script: NmeaSampleData.txt where there are 4 satellites on a line, for instance line 5 we have:-
$GPGSV,3,1,12,04,16,162,46,07,84,207,48,08,34,135,45,09,17,315,38*74

but only the first 3 of them are recognized.
It could be because the checksum symbol '*' is fouling it up.
I wish I could fix this myself but the code is excellently written and I do not have to skill to do this -sorry.

**Comment by dotMorten** [comment]
Thank you for reporting this. I _cannot_ believe no one ever noticed this. It's easily reproducible. Good catch! I'll have that fixed in a few....

**Comment by dotMorten** [comment]
Fixed !
