### ISSUE TITLE
Fixing the NMEA GPGSV Parser results does not give a proper installation now

### ISSUE THREAD

**Issue by gordonpagan** [dotMorten/NmeaParser#31]
Thank you for the quick update of the parsing issue dotMorten. Now I am not quite sure why I find this difficult because the previous Gitub installation was not a problem to install and load up into VS17. Looking at just the Desktop installation, I build the NmeaParser.WinDesktop.dll first and then build the SampleApp.WinDesktop after. Unfortunately in this current version the executable is not finding the dll. If I botch together in the same directory the current dll from the OBJ directory in NmeaParser.WindDesktop and   NmeaSampleData.txt, System.Numerics.Vectors.dll and also SampleApp.WinDesktop.exe from the previous version that works fine on my system and I get 11+ satellite vehicles visible on the skyplot. I am not sure whether I have made an error myself or if there is some greater issue. This library is engineered superbly. I hope this minor glitch can be ironed out.

**Comment by dotMorten** [comment]
When building the SDK you should use the NuGet package that's created, rather than doing an assembly reference.
