### ISSUE TITLE
CloseAsync

### ISSUE THREAD

**Issue by terribletim** [dotMorten/NmeaParser#33]
Hi - looking at [NmeaDevice.CloseAsync](https://github.com/dotMorten/NmeaParser/blob/master/src/NmeaParser.Shared/NmeaDevice.cs#L100) following some issues when implementing in WCF service, and wondering if `await closeTask.Task;` is in the right place.

In existing code below, if **m_cts** is null then `await closeTask.Task `will block indefinitely:
		`

			if (m_cts != null)
			{
				closeTask = new TaskCompletionSource<bool>();
				if (m_cts != null)
					m_cts.Cancel();
				m_cts = null;
			}
			await closeTask.Task;
			await CloseStreamAsync(m_stream);
			MultiPartMessageCache.Clear();
			m_stream = null;
			lock (m_lockObject)
				IsOpen = false;
		`

Should this be changed to:
		`

			if (m_cts != null)
			{
				closeTask = new TaskCompletionSource<bool>();
				m_cts.Cancel();
				await closeTask.Task;
				m_cts = null;
			}
			await CloseStreamAsync(m_stream);
			MultiPartMessageCache.Clear();
			m_stream = null;
			lock (m_lockObject)
				IsOpen = false;
		`

with locks on m_cts to handle potential race condition with **Dispose**? 

Similarly, in relation to `await CloseStreamAsync(m_stream);` which may also be called during Dispose, implementation of `CloseStreamAsync` in **SerialPortDevice** should check if port **IsOpen** before calling **Close** (as first call to **Close** _invokes the protected SerialPort.Dispose(Boolean)_ )

**Comment by dotMorten** [comment]
I believe this issue has been addressed as part of some recent refactoring
