### ISSUE TITLE
Using project for Xamarin and iOS

### ISSUE THREAD

**Issue by alirezaahmadi** [dotMorten/NmeaParser#40]
Hi, 
I wanted to know how can I use this library in Xamarin for iOS, can you help me ? 
Thanks ...

**Comment by dotMorten** [comment]
You need to open a Bluetooth stream connection to your GPS, then pass that into a StreamDevice. I don't have any specific examples how to do this in iOS, or any specific iOS devices, as I don't own an iPhone to test on. If you figure it out, feel free to share your solution here.
