### ISSUE TITLE
Cannot add custom Nmea message type

### ISSUE THREAD

**Issue by XPD-Kasun** [dotMorten/NmeaParser#41]
I tried to add a custom nmea type called GPVTG. 
 ```
[NmeaMessageType("GPVTG")]
  public class GPVTG : NmeaMessage
    {
        protected override void OnLoadMessage(string[] message)
        {
        }
    }
```

But this method (OnLoadMessage) doesnt get called even GPVTG message comes through the COM port nmea channel. Is there any registration needs to be done other than adding NmeaMessageType attribute?

**Comment by dotMorten** [comment]
It would only work if it's part of the same assembly as the other assemblies.

**Comment by XPD-Kasun** [comment]
I used the nuget version of this parser. So I cannot modify the assembly. In order to add this to the same assembly I have to rebuild from the source, dont I?

**Comment by dotMorten** [comment]
Yes

**Comment by dotMorten** [comment]
Yes. Alternatively, just listen for messages, and when you get an "UnknownMessage", just parse it yourself then and there.

**Comment by XPD-Kasun** [comment]
I think it is the way to go.

**Comment by dotMorten** [comment]
Also I added issue #42
