### ISSUE TITLE
Allow registering other assemblies that declares messages

### ISSUE THREAD

**Issue by dotMorten** [dotMorten/NmeaParser#43]
Currently only the message types in the main assemblies are auto-discovered. Provide a mechanism for registering more assemblies that contain NMEA messages.

Coming out of suggestion here: https://github.com/dotMorten/NmeaParser/issues/41#issuecomment-407743695

**Comment by terribletim** [comment]
Is this the same as issue #8?

**Comment by dotMorten** [comment]
@terribletim That's a PR not an issue ;-) I prefer issues first where we discuss its merits, before big PRs
