### ISSUE TITLE
GnssMonitor: picking up GN* messages

### ISSUE THREAD

**Issue by HG-Dev** [dotMorten/NmeaParser#78]
I've been trying to figure out why GnssMonitor.OnMessageReceived has been interpreting exactly one real GGA message before going silent, and I think it might be the m_supportGNMessages flag.

Here's an idea of what my log looks like:
```
(OnMessageReceived) Gga receieved (right after else if (message is Gga gga))
(OnLocationUpdate) {lat, lon, alt, satellites}
(NmeaMessageReceived end) Gga message should have been processed
///
(NmeaMessageReceived end) Gga message should have been processed
(The message contained "GGA" but wasn't picked up by OnMessageReceived? Weird)
///
(NmeaMessageReceived end) Gga message should have been processed
///
(NmeaMessageReceived end) Gga message should have been processed
///
(NmeaMessageReceived end) Gga message should have been processed
///
Ignoring message in favor of Gsv (the m_supportGNMessages return)
(NmeaMessageReceived end) Gga message should have been processed
///
Ignoring message in favor of Gsv
(NmeaMessageReceived end) Gga message should have been processed
```

Assuming my device (a Bad Elf GPS Pro+) supports GN* messages, where are they interpreted?

**Comment by dotMorten** [comment]
GN is the combined message. Once it's detected that the device uses GN that is what is used for GGA.

**Comment by HG-Dev** [comment]
Is this delivered in one string, or compiled over time? I've confirmed that OnLocationUpdate only works if this GN* flag is ignored.

**Comment by dotMorten** [comment]
I'm not really following what your issue is. Could you perhaps share a sample NMEA log from your device?

**Comment by HG-Dev** [comment]
Okay. I'll be sure to identify where LocationChanged (whoops, not "OnLocationChanged") is firing.

**Comment by HG-Dev** [comment]
[badelf_nmea.log](https://github.com/dotMorten/NmeaParser/files/5148985/badelf_nmea.log)
As noted, LocationChanged is called only once. PropertyChanged is called so long as the given message is not GGA or RMC. I don't see any other areas updating coordinates, though...

**Comment by dotMorten** [comment]
Is the location actually changing?

**Comment by HG-Dev** [comment]
No. Once the first Gga message is parsed for coordinates, the coordinates (GnssMonitor.Latitude / GnssMonitor.Longitude) never change again, and so LocationChanged is never called again.

**Comment by dotMorten** [comment]
If your location isn't changing it makes sense that the location changed event doesn't fire then, right?
Anyway I'll take a look at the log a bit later

**Comment by HG-Dev** [comment]
Sure, if I was standing stock still with fantastic precision on the part of my GPS receiver. For this log, I walked in a big circle.

**Comment by dotMorten** [comment]
Ok you just said the location wasn't changing. Sounds like we misunderstood each other 😂

**Comment by dotMorten** [comment]
Looking at the log, your bad elf is weird ;-) It supports GN messages, but it only uses it for GSA, and everything else is GP for location.
Did you configure your device to report messages like this, or is that just how the bad elf receiver works?

**Comment by dotMorten** [comment]
@HG-Dev I'm also seeing in the log you shared that almost all the messages have invalid checksums, and thus fail to parse

**Comment by HG-Dev** [comment]
Yeah-- I still don't quite understand what GN messages are, but even I can tell they're not in there. The website specifies that it should have "GGA, GSA, GSV, RMC - Talker ID's GP,GL,GN." I guess I'll contact the maker to confirm what's going on.

The Bad Elf device has only two settings for NMEA, "Default (all NMEA sentences)" and "Simplified NMEA (GGA / RMC only)." I wouldn't worry about the checksums; the text between $ and * all check out with [this website](https://nmeachecksum.eqth.net/).

**Comment by dotMorten** [comment]
GP*** : GPS Satellites
GL*** : GLONASS Satellites
etc.
GN***: Combination of all satellites (and usually the one you want to use).

Never fully understood why we need location updates for each constellation, but it makes things tricky because we have to detect that this is a multi-band receiver, and we want to prefer the GN messages over the individual measurements, since this gives the most satellites for the solution fix.

**Comment by dotMorten** [comment]
It looks like I should probably detect if there's a GN version for each message type instead. I'll submit a fix for that. Thanks for testing this out and providing the feedback

**Comment by HG-Dev** [comment]
Very illuminating, thanks! Glad to help.

**Comment by dotMorten** [comment]
You're welcome. It seems rather odd that you're getting `GPGGA` messages but not `GNGGA`. Found this on the @badelf website and it makes no sense to me:
![image](https://user-images.githubusercontent.com/1378165/91797042-7794f180-ebd6-11ea-85e5-da9e6b52f146.png)
Basically you only get `GGA` from the GPS system, but no `GGA` from GLONASS, or a combined one of them (I'm assuming `GPGGA` probably is the combined value but using the wrong identifier)

**Comment by HG-Dev** [comment]
Followup: You're right, GPGGA is the combined value. In their support's words, "the Pro+ is built on a dual-frequency GNSS engine from Mediatek, it defaults to the talker identifier for for GPS (GP) for many of the messages regardless of whether the GLONASS signal is contributing to the solution."

**Comment by dotMorten** [comment]
Thanks for the follow-up. That's definitely against the NMEA spec but I can see why. Older NMEA libraries would likely only pass `GP***` messages (including some older versions of this library).
Anyway the latest fix I made should address this
