### ISSUE TITLE
NmeaDevice sender vs object sender in message received delegate

### ISSUE THREAD

**Issue by davidbenncsiro** [dotMorten/NmeaParser#87]
https://dotmorten.github.io/NmeaParser/concepts/index.html says that message delegate signature is:
~~~
private void device_NmeaMessageReceived(NmeaDevice sender, NmeaMessageReceivedEventArgs args)
~~~
but I have found that it needs to be:
~~~
private void device_NmeaMessageReceived(object sender, NmeaMessageReceivedEventArgs args)
~~~
i.e. `object sender` not `NmeaDevice sender`. Perhaps I have misunderstood something but I see errors with the latter but not the former.

Thanks for the NmeaParser library.

**Comment by dotMorten** [comment]
Thanks. Should be updated in a few minutes once the CI job is done.
