### ISSUE TITLE
GSV Signal ID

### ISSUE THREAD

**Issue by stealthrabbi** [dotMorten/NmeaParser#92]
The NMEA GSV parser doesn't include the Signal ID, I believe. I'm not sure what NMEA spec version this library. Is it possible to get this value out of the message, if the GSV message being parsed meets that spec?

https://www.nmea.org/Assets/20190627%20GDC%20Amendment.pdf

**Comment by dotMorten** [comment]
It doesn't ? https://dotmorten.github.io/NmeaParser/api/netcore/NmeaParser.Messages.Gsv.GnssSignalId.html#NmeaParser_Messages_Gsv_GnssSignalId

**Comment by stealthrabbi** [comment]
Ah no, I am on 2.1. I didn't see it in the release notes for 2.2 so I have not upgraded. Will upgrade! Thank you!
