### ISSUE TITLE
Installing SampleApp on Desktop

### ISSUE THREAD

**Issue by linngn** [dotMorten/NmeaParser#96]
Hi,
I want to transfer GPS data from an external receiver through PC via Bluetooth, and I found that your repo is very helpful for me. But I don't know how to install your sample app and failed to build NmeaParser.sln.
Can you show me some instructions to use your repo, that would help a lot for my project :)

**Comment by dotMorten** [comment]
> failed to build NmeaParser.sln

What failed? Please share the errors you're getting and which version of VS you use. You're probably just missing some required workdloads.
