### ISSUE TITLE
CPU usage is high

### ISSUE THREAD

**Issue by mclifford1** [dotMorten/NmeaParser#98]
Hello, 

I've recently updated from using the 1.X to the 2.X version of this (via NuGet) and noticed that the CPU usage of my application is around %40 when running with the debugger, or up to %90+ when running standalone.   Obviously this isn't ideal.

I've isolated the cause as this library and more specifically, the read loop in NmeaDevice (lines 74-92) as it sits in a tight loop.  I've added a delay when no bytes are read as a temp fix.

![image](https://user-images.githubusercontent.com/11770136/145708560-aa2705c3-f2ff-407c-9c94-2099984c4b97.png)

Mark

**Comment by dotMorten** [comment]
See this comment and the thread below: https://github.com/dotMorten/NmeaParser/issues/83#issuecomment-748048768

You shouldn’t have to add the delay. The readasync method is supposed to do that and not return until data is received.

**Comment by mclifford1** [comment]
I have just read through that other bug report, which is very similar to what I am seeing.

For now I am testing with just an NMEA file sample and the behaviour (as with #83 ) is the same in the sample application provided.
![image](https://user-images.githubusercontent.com/11770136/145731592-3562ce66-6328-49f3-bf30-a44eaa574ebe.png)


It does seem that the Stream.ReadAsync() returns immediately with 0 bytes most of the time.  I added some debug to capture how many reads it's doing per second:

![image](https://user-images.githubusercontent.com/11770136/145730497-3705e489-8b26-46b9-b276-84415578647f.png)

I think because BufferedStream is implementing Read in a non-blocking way, the calling ReadAsync is also non-blocking?

If I tweak the Read method to "block" then things calm down a lot:
![image](https://user-images.githubusercontent.com/11770136/145731538-c0ddcf42-3d0b-45f3-a164-ec68fa405345.png)

![image](https://user-images.githubusercontent.com/11770136/145731548-13f95bb8-6167-4a52-aa4f-d760d5901a28.png)

![image](https://user-images.githubusercontent.com/11770136/145731559-e4b39b0b-c352-42a1-b5db-145dfc9352b5.png)

**Comment by dotMorten** [comment]
@mclifford1 Nice catch. Yeah I think the Read should block until the buffer has been populated, but I'd probably do that a bit different.
At least you shouldn't see this high CPU usage with a normal device.

**Comment by dotMorten** [comment]
@mclifford1 The above referenced commit brought my CPU usage from ~16% down to between 0 and 0.1%. Thanks for reporting and finding this!

**Comment by mclifford1** [comment]
Hey no problem, keep up the good work!
